version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    container_name: es
    environment:
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.zen.minimum_master_nodes=1
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    ports:
     - "9200:9200"
    networks:
      elk:
        aliases:
          - es
  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    restart: always
    ports:
     - "5601:5601"
    networks:
      elk:
        aliases:
          - kibana
    depends_on:
      - es
  packetbeat:
    image: docker.elastic.co/beats/packetbeat:6.0.0
    container_name: packetbeat
    privileged: true
    volumes:
      - ./packetbeat/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml
    restart: always
    network_mode: host
    depends_on:
      - kibana
networks:
  elk: