metricbeat.modules:
- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - core
    - diskio
    - socket
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory
  ticks: false
output.elasticsearch:
  hosts: ["es:9200"]
setup.kibana:
  host: "kibana:5601"
setup.dashboards.enabled: true