metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - memory
    - network
    - process
  enabled: true
  period: 10s
  processes: ['.*']
  ticks: false
output.elasticsearch:
  hosts: ["es:9200"]
setup.kibana:
  host: "kibana:5601"
setup.dashboards.enabled: true